---
# installs the apt proxy

- name: Install apt proxy packages
  ansible.builtin.apt:
    name: apt-cacher-ng
    state: present
  tags:
    - apt-proxy

- name: Install apt-cacher-ng template
  ansible.builtin.template:
    src: acng.conf.j2
    dest: /etc/apt-cacher-ng/acng.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart apt-cacher-ng
  tags:
    - apt-proxy

- name: Security settings
  ansible.builtin.template:
    src: security.conf.j2
    dest: /etc/apt-cacher-ng/security.conf
    owner: root
    group: apt-cacher-ng
    mode: "0640"
  notify: Restart apt-cacher-ng
  tags:
    - apt-proxy

- name: Include web acces
  ansible.builtin.import_tasks: webaccess.yml
  when: aptproxy_include_web
  tags:
    - apt-proxy
