- name: install web
  apt: name={{ item }} state=present
  with_items:
  - lighttpd

- name: update cache
  apt: update_cache:yes

- name: install bandwidthd
  apt: name=bandwidthd state=present
  
- name: add bandwidthd symlink
  file: state=link src=../../lib/bandwidthd/htdocs dest=/var/www/html/bandwidthd
