---
- name: Restart apt-cacher-ng
  become: true
  ansible.builtin.service:
    name: apt-cacher-ng
    state: restarted

- name: Restart webserver
  become: true
  ansible.builtin.service:
    name: lighttpd
    state: restarted

- name: Restart bandwidthd
  become: true
  ansible.builtin.service:
    name: bandwidthd
    state: restarted
