---
- name: Restart apt-cacher-ng
  ansible.builtin.service:
    name: apt-cacher-ng
    state: restarted

- name: Restart webserver
  ansible.builtin.service:
    name: lighttpd
    state: restarted

- name: Restart bandwidthd
  ansible.builtin.service:
    name: bandwidthd
    state: restarted
